# List of primary types

# Finished Cities: Chicago, Detroit, San Francisco, Seattle, Honolulu, Baltimore, Washington

property <- c("ARSON", "BURGLARY", "CRIMINAL DAMAGE", "CRIMINAL TRESPASS", "MOTOR VEHICLE THEFT", "THEFT", "LARCENY", "STOLEN VEHICLE", "VANDALISM", "LARCENY/THEFT", "VEHICLE THEFT", "TRESPASS", "FRAUD", "FORGERY/COUNTERFEITING", "EMBEZZLEMENT", "STOLEN PROPERTY", "BAD CHECKS", "TREA", "RESIDENTIAL BURGLARIES", "PROPERTY DAMAGE", "AUTO RECOVERIES", "RECOVERED VEHICLE", "PROPERTY - MISSING, FOUND", "COMMERCIAL BURGLARIES", "AUTO THEFTS", "FRAUD CALLS", "VEHICLE BREAK-IN/THEFT", "THEFT/LARCENY", "AUTO THEFT", "LARCENY FROM AUTO", "THEFT/OTHER", "THEFT F/AUTO")

violent <- c("ASSAULT", "BATTERY", "CRIM SEXUAL ASSAULT", "DOMESTIC VIOLENCE", "HOMICIDE", "HUMAN TRAFFICKING", "INTIMIDATION", "KIDNAPPING", "ROBBERY", "SEX OFFENSE", "STALKING", "WEAPONS VIOLATION", "AGGRAVATED ASSAULT", "DISORDERLY CONDUCT", "SEX OFFENSES, FORCIBLE", "FAMILY OFFENSES", "LOITERING", "SEX OFFENSES, NON FORCIBLE", "EXTORTION", "DISTURBANCES", "NUISANCE, MISCHIEF COMPLAINTS", "ASSAULTS", "PROWLER", "HAZARDS", "CAR PROWL", "VICE CALLS", "THREATS, HARASSMENT", "CASUALTIES", "RECKLESS BURNING", "GUN CALLS", "WEAPONS CALLS", "SEX OFFENSE (NO RAPE)", "ROBBERY - RESIDENCE", "SHOOTING", "AGG. ASSAULT", "COMMON ASSAULT", "ROBBERY - STREET", "ROBBERY - COMMERCIAL", "ROBBERY - CARJACKING", "ASSAULT BY THREAT", "RAPE", "ASSAULT W/DANGEROUS WEAPON", "SEX ABUSE")

other <- c("CONCEALED CARRY LICENSE VIOLATION", "DECEPTIVE PRACTICE", "GAMBLING", "INTERFERENCE WITH PUBLIC OFFICER", "LIQUOR LAW VIOLATION", "NARCOTICS", "NON-CRIMINAL", "OBSCENITY", "OFFENSE INVOLVING CHILDREN", "OTHER NARCOTIC VIOLATION",  "OTHER OFFENSE", "PROSTITUTION", "PUBLIC INDECENCY", "PUBLIC PEACE VIOLATION", "RITUALISM", "SECONDARY CODES", "DRUG/NARCOTIC", "WARRANTS", "OTHER OFFENSES", "WEAPON LAWS", "MISSING PERSON", "DRIVING UNDER THE INFLUENCE", "SUSPICIOUS OCC", "DRUNKENNESS", "LIQUOR LAWS", "RUNAWAY", "BRIBERY", "PORNOGRAPHY/OBSCENE MAT", "SUICIDE", "TRAFFIC RELATED CALLS", "SUSPICIOUS CIRCUMSTANCES", "MENTAL CALL", "LIQUOR VIOLATIONS", "NARCOTICS COMPLAINTS", "PARKING VIOLATIONS", "MISCELLANEOUS MISDEMEANORS", "NOISE DISTURBANCE", "ANIMAL COMPLAINTS", "PERSONS - LOST, FOUND, MISSING", "BURGLARY ALARMS (FALSE)", "VEHICLE ALARMS (FALSE)", "WARRANT CALLS", "BURGLARY ALACAD (FALSE)", "PARKS EXCLUSIONS", "CRISIS CALL", "PANIC ALARMS (FALSE)", "HARBOR CALLS", "VEHICLE ALACAD (FALSE)", "PANIC ALACAD (FALSE)", "PUBLIC GATHERINGS", "NULL", " ", "")

find_prim_type <- function(a){
	return (ifelse(a %in% property, "PROPERTY", ifelse(a %in% violent, "VIOLENT", "OTHER")))
}

find_new_prim_type <- function(df){
	list <- c(unique(df$Primary.Type))
	new <- c()
	for (a in list) {
		if ( a %in% property | a %in% violent | a %in% other ) {}
		else { new <- c(new, a) }
	}
	return (new)
}
